import type { Metadata } from "next";
import "@/styles/global.css";
import { Header } from "@/share/Header";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className="px-[16px] lg:px-[40px]">
        <Header />
        {children}
      </body>
    </html>
  );
}
